name: CI/CD

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore
      run: dotnet restore source/CecoChat.sln

    - name: Build
      run: dotnet build --no-restore source/CecoChat.sln

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Setup Docker Build
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Publish .NET projects
      run: dotnet publish source\CecoChat.Connect.Server\CecoChat.Connect.Server.csproj -o .\connect -c Debug

    - name: Build and push Docker images
      id: dockerbuild
      uses: docker/build-push-action@v2
      with:
        file: containerize/Connect.Dockerfile
        push: true
        tags: ceco.com/cecochat/connect:0.1
